version: '3'
# Other docker-compose examples in /examples

services:
  minecraft:
    image: itzg/minecraft-server
    ports:
      - "25565:25565"
    volumes:
      - "mc:/data"
    environment:
      EULA: "TRUE"
      ENABLE_AUTOPAUSE: "TRUE"
      OVERRIDE_SERVER_PROPERTIES: "TRUE"
      MAX_TICK_TIME: "-1"
      MAX_PLAYERS: "12"
      VIEW_DISTANCE: "32"
      OPS: "thiagomadpin"
      SEED" "thiagomadpin"
    restart: always
volumes:
  mc: {}
